name:  basic workflow

on: 
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Show the workflow trigger
        run: echo "Triggered by ${{ github.event_name }}"