name:  basic workflow-1

# Events that trigger workflows
on: 
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *' # Run every day at midnight UTC
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Show the workflow trigger
        run: echo "Triggered by ${{ github.event_name }}"