name: Runners Demo

on: workflow_dispatch # Initial value is push, updated to not accidently run when pushing to github

jobs:
    job-1-linux-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an Ubuntu runner"
                echo "Runner OS: $RUNNER_OS"
    job-2-windows-runner:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo "This job is running on a Windows runner."
                echo "Runner OS: $RUNNER_OS"