name: Event Filters and Activity Types demo
on:
    pull_request:
        types:
            - opened
            - synchronize
            - closed 
        branches:
            - main
jobs:
    echo-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is opened or synchronized AND base branch is main"